# ベースイメージを指定する
FROM python:3.8-slim

# ワーキングディレクトリを設定する
WORKDIR /usr/src/app

# アプリケーションの依存関係をインストールする
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションのコードをコピーする
COPY . .

# アプリケーションを実行する
CMD ["python", "./app.py"]
