version: '3'
services:
  web:
    build:
      context: ./web
    ports:
      - "8000:8000"

  db:
    build:
      context: ./db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

